# Generated by Django 5.2.7 on 2025-11-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='resume_pdf',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
