# Generated by Django 5.2.7 on 2025-11-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0003_alter_personalinfo_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile.avif', null=True, upload_to='profile/'),
        ),
    ]
